var arr1 = [1, 2, 3];
var arr2 = [1, 2, 3];
console.log(arr1);
console.log(arr2);
var john = { name: 'John', age: 25 };
var jane = { name: 'Jane', age: 27 };
var Jack = { name: 'Jack' };
var rick = { name: 'Rick', age: 31 };
;
;
;
var arr = [1, 2, 3];
arr[0] = 7;
console.log(arr);
var obj = { a: 1, b: 2 };
obj.b = 5;
console.log(obj);
